blog/apps/post/urls.py
from django.urls import path, include
import apps.post.views as views

app_name = 'post'

urlpatterns = [
    path('posts/',views.PostListView.as_view(), name="post_list"),
    path('posts/create', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/<slug:slug>/update', views.PostUpdateView.as_view(), name="post_update"),
    path('posts/<slug:slug>/delete', views.PostDeleteView.as_view(), name="post_delete"),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, not_found_view, internal_error_view, forbidden_view, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
    path('about/', AboutView.as_view(), name='about')
]
# Manejadores de errores
handler404 = not_found_view
handler500 = internal_error_view
handler403 = forbidden_view
# Los manejadores estan disponibles en cualquier parte de la aplicación,
# por lo que no es necesario importarlos en cada vista.
# o incluso aqui en blog\blog\urls.py

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                            document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root = settings.MEDIA_ROOT)
    

blog/templates/about.html
{% extends 'layouts/general_layout.html' %}

<!doctype html>
<html lang="en">
    <head>
        <title>ABOUT</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            {% block content %}
            <h1>Sobre el Proyecto: </h1>
            <span class="text-black-500 font-bold text-lg">
                <br>Este Blog es el trabajo final que se realizo en el curso: Informatorio. 
Es un programa del Gobierno de la Provincia del Chaco que comenzó
en 2012 para capacitar en desarrollo web a jóvenes (y no tan jovenes, estoy en grupo "no tan").

<br>
<br>¡¡!!BIENVENIDOS!!¡¡ a este Blog,donde exploramos las ideas con ligereza,pero sin perder profundidad.
<br>
<br>Aquí, todo se mezcla, se teje de manera personal y subjetiva: desde los saberes
de las doctrinas orientales y las religiones occidentales, hasta pasajes de libros sagrados, 
conocimientos no oficiales, y pseudociencias (sí, incluso la psicología —léase con humor, porque con humor lo decimos—). 

<br>
<br>Bienvenidos a TEJER todo.
            </span>
            {% endblock content %}
        </header>
        <main></main>
        <footer>
            <!-- place footer here -->
        </footer>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog/templates/index.html
{% extends 'layouts/general_layout.html' %}

<!doctype html>
<html lang="en">
    <head>
        <title>Title</title>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta
            name="viewport"
            content="width=device-width, initial-scale=1, shrink-to-fit=no"
        />

        <!-- Bootstrap CSS v5.2.1 -->
        <link
            href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
            rel="stylesheet"
            integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
            crossorigin="anonymous"
        />
    </head>

    <body>
        <header>
            {% block content %}
            <div style="background-color: rgb(240, 223, 44); display: flex; flex-direction: row; justify-content: space-between;">
                {% for category in categories %}
                <a href="{% url 'post:post_list' %}?category={{category.id}}">{{category.title}}</a>
                {% endfor %}
                <h1></h1>
            </div>
            <h1 style="font-family: serif; font-size: 50px; font-style: italic; color: black;">Blog <br><mark>TEJER todo</mark></h1>
        
            <!-- place navbar here -->
            <h2>Hecho con amor</h2>
            <br>
            <h3 style="font-style: italic; color: black; font-size: 20px;">Posts destacados:</h3>
            <br>
            <div class="container">
                <div class="row">
                    {% for post in random_posts %}
                        <div class="bg-gray-800 text-white rounded-2xl p-6">
                            <h3 class="text-2xl uppercase font-bold">{{post.title}}</h3>
                            <p>{{ post.content|truncatewords:20 }}</p>
                            {% if post.images.exists %}
                            <img width="100px" src="{{ post.images.first.image.url }}" alt="Imagen del post">
                            {% endif %}
                            <p>Publicado por: <strong class="font-bold">{{ post.author.username}}
                            </strong></p>
                            <p>Fecha de publicacion: {{ post.creation_date }}</p>
                            <p>Comentarios permitidos:  {{ post.allow_comments|yesno:"Si,No" }} </p>
                            <p>categoria: {{post.category}} </p>
                            <div class="flex gap-2 mt-8">
                                <a 
                                class="bg-red-500 text-white p-2 rounded-lg"
                                href="{% url 'post:post_detail' slug=post.slug %}"
                                >Leer más</a>
                            </div>
                        </div>
                        <br>
                    {% endfor %}
                </div>
            </div>
        {% endblock content %}
        </header>
        <!-- Bootstrap JavaScript Libraries -->
        <script
            src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
            integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
            crossorigin="anonymous"
        ></script>

        <script
            src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
            integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
            crossorigin="anonymous"
        ></script>
    </body>
</html>

blog/templates/post_delete.html
{% extends 'layouts/post_layout.html' %}

{% block title %}BORRAR Post | BLOG TEJER{% endblock title %}

{% block content %}
<h2>¿Estás seguro de que deseas eliminar este post?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Sí, eliminar</button>
</form>

<a href="{% url 'post:post_detail' slug=object.slug %}">Cancelar</a>
{% comment %} <a href="javascript:history.back()">Cancelar</a>  {% endcomment %}
{% endblock content %}