blog/apps/post/urls.py
from django.urls import path, include
import apps.post.views as views

app_name = 'post'

urlpatterns = [
    path('posts/',views.PostListView.as_view(), name="post_list"),
    path('posts/create', views.PostCreateView.as_view(), name="post_create"),
    path('posts/<slug:slug>/', views.PostDetailView.as_view(), name='post_detail'),
    path('posts/<slug:slug>/update', views.PostUpdateView.as_view(), name="post_update"),
    path('posts/<slug:slug>/delete', views.PostDeleteView.as_view(), name="post_delete"),
    path('posts/<slug:slug>/comments/create/', views.CommentCreateView.as_view(), name='comment_create'),
    path('comments/<uuid:pk>/update/', views.CommentUpdateView.as_view(), name='comment_update'),
    path('comments/<uuid:pk>/delete/', views.CommentDeleteView.as_view(), name='comment_delete'),
]

blog/apps/user/urls.py
from django.urls import path
import apps.user.views as views

app_name = 'user'

urlpatterns = [
    path('user/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('auth/register/', views.RegisterView.as_view(), name="auth_register"),
    path('auth/login/', views.LoginView.as_view(), name="auth_login"),
    path('auth/logout/', views.LogoutView.as_view(), name="auth_logout"),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from blog.views import IndexView, not_found_view, internal_error_view, forbidden_view, AboutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', IndexView.as_view(), name='home'),
    path('', include('apps.user.urls')),
    path('', include('apps.post.urls')),
    path('about/', AboutView.as_view(), name='about')
]
# Manejadores de errores
handler404 = not_found_view
handler500 = internal_error_view
handler403 = forbidden_view
# Los manejadores estan disponibles en cualquier parte de la aplicación,
# por lo que no es necesario importarlos en cada vista.
# o incluso aqui en blog\blog\urls.py

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.STATIC_URL,
                            document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                            document_root = settings.MEDIA_ROOT)
    

blog/apps/post/models.py
from django.db import models
from django.utils import timezone 
from django.conf import settings
from django.utils.text import slugify
import os
import uuid


class Category(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    title = models.CharField(max_length=200)
    description = models.TextField()

    def __str__(self):
        return self.title

class Post(models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True, max_length=200, blank= True)
    content = models.TextField(max_length=10000)
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    creation_date = models.DateTimeField(default=timezone.now) 
    modification_date = models.DateTimeField(auto_now=True)
    allow_comments = models.BooleanField(default=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE,related_name='categories')


    def __str__(self):
        return self.title
    
    @property
    def amount_comments(self):
        return self.allow_comments.count() 
    
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)
        #todo : definir imagen de portada

    def generate_unique_slug(self):
        slug = slugify(self.title)
        unique_slug = slug
        num = 1

        while Post.objects.filter(slug=unique_slug).exists():
            unique_slug = f'{slug}-{num}'
            num += 1
        return unique_slug


class Comment(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,editable=False)
    content = models.TextField(max_length=500)
    creation_date = models.DateTimeField(auto_now_add=True)
    author = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    post = models.ForeignKey(Post, on_delete=models.CASCADE,related_name='comments')

    def __str__(self):
        return self.content

def get_image_filename(instance, filename):
    post_id = instance.post.id
    images_count = instance.post.images.count()
    base_filename, file_extension = os.path.splitext(filename)
    new_filename = f"post_{post_id}_cover_{images_count + 1}{file_extension}"
    return os.path.join('post/cover/', new_filename)    

class PostImage(models.Model):
    post = models.ForeignKey(
        Post, on_delete=models.CASCADE, related_name='images')
    image = models.ImageField(upload_to=get_image_filename,
default='post/default/post_default.png')
    active = models.BooleanField(default=True)

    def __str__(self):
        return f"PostImage {self.id}"
    
def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = self.generate_unique_slug()
        super().save(*args, **kwargs)

        if not self.images.exists():
            PostImage.objects.create(post=self,
image='post/default/post_default.png')

blog/apps/post/forms.py
from django import forms
from apps.post.models import Comment
from apps.post.models import Post, PostImage, Category


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']

        label = {
            'content': 'Comentario'
        }

        widgets = {
            'content': forms.Textarea(attrs={'rows':3, 'placeholder': 'Escribe tu'
'comentario...', 'class': 'p-2'})
        }

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content', 'allow_comments', 'category')
        categories = forms.ModelMultipleChoiceField(  # Este es el nuevo campo
        queryset=Category.objects.all(),  # Obtiene todas las categorías disponibles
        widget=forms.CheckboxSelectMultiple,  # Puedes usar otro widget si prefieres
        required=False
    )

    class Meta:
        model = Post
        fields = ('title', 'content', 'allow_comments', 'category')  # Incluye 'categories'

class NewPostForm(PostForm):
    image = forms.ImageField(required=False)

    def save(self, commit = True):
        post = super().save(commit=False)
        image = self.cleaned_data['image']

        if commit:
            post.save()
            
            if image:
                PostImage.objects.create(post=post, image=image)
        return post
    
class UpdatePostForm(PostForm):
    image = forms.ImageField(required=False)

    def __init__(self, *args, **kwargs):
    # Obtenemos las imágenes activas del post que se quiere actualizar
        self.active_images = kwargs.pop('active_images', None)
        super(UpdatePostForm, self).__init__(*args, **kwargs)

        if self.active_images:
            for image in self.active_images:
                field_name = f"keep_image_{image.id}"
                self.fields[field_name] = forms.BooleanField(
                    required=False, initial=True, label=f"Mantener {image}"
            )
    def save(self, commit=True):
        post = super().save(commit=False)
        if commit:
            post.save()
            if self.cleaned_data['image']:         # Si el usuario sube una nueva imagen
                PostImage.objects.create(
                    post=post, image=self.cleaned_data['image'])
        if self.active_images: # Si hay imágenes activas y se quiere mantener alguna
            for image in self.active_images:
                if not self.cleaned_data.get(f"keep_image_{image.id}", True):
                    image.delete() # Eliminar la imagen si el usuario no la quiere mantener, checkboxes desmarcados
        return post
    
class PostFilterForm(forms.Form):
    search_query = forms.CharField(
        required = False,
        widget=forms.TextInput(attrs={'placeholder': 'Buscar...', 'class': 'w-fullp-2'})
    )
    order_by = forms.ChoiceField(
        required = False,
        choices=(
            ('-creation_date', 'Más reciente'),
            ('creation_date', 'Más antiguo'),
            ('-comments_count', 'Más comentado'),
            ('-title', 'Ascendente'),
            ('title', 'Descendente'),
            # agregar orden alfabetico title 
        ),
        widget=forms.Select(attrs={'class': 'w-full p-2'})
    )

blog/apps/post/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, CreateView, DeleteView, UpdateView
from apps.post.models import Post, PostImage, Comment
from apps.post.models import Post
from django.db.models import Q
from apps.post.forms import NewPostForm, UpdatePostForm, CommentForm, PostFilterForm, Category
from django.urls import reverse, reverse_lazy
from django.conf import settings
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.db.models import Count 



class PostListView(ListView):
    model = Post
    template_name = 'post/post_list.html'
    context_object_name = 'posts'
    paginate_by = 10

    def get_queryset(self):
        queryset = Post.objects.all().annotate(comments_count=Count('comments'))
        search_query = self.request.GET.get('search_query', '')
        order_by = self.request.GET.get('order_by', '-creation_date')
        category = self.request.GET.get('category', '')

        if search_query:
            queryset = queryset.filter(
                Q(title__icontains=search_query) |
                Q(author__username__icontains=search_query) |
                Q(category__title__icontains=search_query)
            )

        if category:
            queryset = queryset.filter(category__id=category)

        return queryset.order_by(order_by)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter_form'] = PostFilterForm(self.request.GET)
        context['categories'] = Category.objects.all()

        if context.get('is_paginated', False):
            query_params = self.request.GET.copy()
            query_params.pop('page', None)

            pagination = {}
            page_obj = context['page_obj']
            paginator = context['paginator']

            if page_obj.number > 1:
                pagination['first_page'] = f'?{query_params.urlencode()}&page={paginator.page_range[0]}'
            if page_obj.has_previous():
                pagination['previous_page'] = f'?{query_params.urlencode()}&page={page_obj.number - 1}'
            if page_obj.has_next():
                pagination['next_page'] = f'?{query_params.urlencode()}&page={page_obj.number + 1}'
            if page_obj.number < paginator.num_pages:
                pagination['last_page'] = f'?{query_params.urlencode()}&page={paginator.num_pages}'

            context['pagination'] = pagination

        return context


class PostCreateView(CreateView):
    model = Post
    form_class = NewPostForm
    template_name = 'post/post_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        post = form.save()

        images = self.request. FILES.getlist('images')

        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)
        else:
            PostImage.objects.create(post=post, image=settings.DEFAULT_POST_IMAGE)
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('post:post_detail', kwargs={'slug': self.object.slug})

class PostDetailView(DetailView):
    model = Post
    template_name = 'post/post_detail.html'
    context_object_name = 'post'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #obtener todas las imagenes activas del post
        active_images = self.object.images.filter(active=True)
        context['active_images'] = active_images
        context['add_comment_form'] = CommentForm()

        #Editar comentarios
        edit_comment_id = self.request.GET.get('edit_comment')
        if edit_comment_id:
            comment = get_object_or_404(Comment, id=edit_comment_id)

            #permitimos editar solo si el usuario logeado es el autor del comentario
            if comment.author == self.request.user:
                context['editing_comment_id'] = comment.id
                context['edit_comment_form'] = CommentForm(instance=comment)
            else:
                context['editing_comment_id'] = None
                context['edit_comment_form'] = None
        
        delete_comment_id = self.request.GET.get('delete_comment')
        if delete_comment_id: 
            comment =  get_object_or_404(Comment, id=delete_comment_id)
            # Permitimos solo si el usuario logueado tiene permiso para eliminar el comentario
            if (
                # Es autor del comentario
                comment.author == self.request.user or
                # Es autor del post, pero el comentario no es de un admin o un superuser
                (comment.post.author == self.request.user and not
comment.author.is_admin and not comment.author.is_superuser) or
                self.request.user.is_superuser or # Es Superuser
                self.request.user.groups.filter(
                    name='Admin').exists() # Es Admin
            ):
                context['deleting_comment_id'] = comment.id
            else:
                context['deleting_comment_id'] = None
            
        return context
    
class PostUpdateView(UpdateView):
    model = Post
    form_class = UpdatePostForm
    template_name = 'post/post_update.html'

    def  get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs['active_images'] = self.get_object().images.filter(
            active=True) # Pasamos las imágenes activas
        return kwargs
    
    def form_valid(self, form):
        post = form.save(commit=False)
        active_images = form.active_images
        keep_any_image_active = False

        # Manejo de las imágenes activas
        if active_images:
            for image in active_images:
                field_name = f"keep_image_{image.id}"
                # Si el checkbox no está marcado, eliminamos la imagen
                if not form.cleaned_data.get(field_name, True):
                    image.active = False
                    image.save()
                else:
                    keep_any_image_active = True

        # Manejo de las nuevas imágenes subidas
        images = self.request.FILES.getlist('images')
        if images:
            for image in images:
                PostImage.objects.create(post=post, image=image)

        # Si no se desea mantener ninguna imagen activa y no se subieron nuevas
#imágenes,
# se agrega una imagen por defecto
        if not keep_any_image_active and not images:
            PostImage.objects.create(
                post=post, image=settings.DEFAULT_POST_IMAGE)
        post.save() # Guardar el post finalmente
        return super().form_valid(form)
    
    def get_success_url(self):
        # El reverse_lazy es para que no se ejecute hasta que se haya guardado el post
        return reverse_lazy('post:post_detail', kwargs={'slug': self.object.slug})

class PostDeleteView(DeleteView):
    model = Post
    template_name =  'post/post_delete.html'
    success_url = reverse_lazy('post:post_list')
    
class CommentCreateView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        form.instance.post = Post.objects.get(slug=self.kwargs['slug'])
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse_lazy('post:post_detail',kwargs={'slug': 
self.object.post.slug})

class CommentUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Comment
    form_class = CommentForm
    template_name = 'post/post_detail.html'
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['pk'])
    
    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug':
self.object.post.slug})

    def test_func(self):
        comment = self.get_object()
        return comment.author == self.request.user
    
class CommentDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Comment
    login_url = reverse_lazy('user:auth_login')

    def get_object(self):
        return get_object_or_404(Comment, id=self.kwargs['pk'])
    
    def get_success_url(self):
        return reverse_lazy('post:post_detail', kwargs={'slug':
self.object.post.slug})
    
    def test_func(self):
        comment = self.get_object()

        is_comment_author = self.request.user == comment.author

        is_post_author = (
            self.request.user == comment.post.author and
            not comment.author.is_admin and
            not comment.author.is_superuser
        )

        is_admin = self.request.user.is_superuser or self.request.user.groups.filter(
            name='Admins').exists()

        return is_comment_author or is_post_author or is_admin

blog/templates/post/post_create.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG TEJER{% endblock title %}

{% block content %}

<h2>Crear nuevo post</h2>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="flex flex-col gap-4">
        <p class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</p>
        <p class="flex flex-col">
            <label for="id_content">Contenido:</label> {{ form.content }}
        </p>
        <p>{{ form.allow_comments.label_tag }} {{ form.allow_comments }}</p>
        <p class="flex flex-col">{{ form.category.label_tag }} {{ form.category }}</p>
        <p><input type="file" name="images" multiple /></p>
    </div>

    <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">
        Crear Post
    </button>
</form>

{% endblock content %}

blog/templates/post/post_delete.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Borrar Post{% endblock title %}

{% block content %}
<h2>Esta seguro que desea eleminar el Post?</h2>
<form method="post">
    {% csrf_token %}
    <button type="submit">Si, eleminar</button>
</form>
<a href="{% url 'post:post_detail' slug=object.slug %}">Cancelar</a>
{% comment %}
<a href="javascript:history.back()">Cancelar</a>
{% endcomment %}
{% endblock content %}

blog/templates/post/post_detail.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG TEJER{% endblock title %}

{% block content %}

{% if active_images %}
    <div class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 gap-4">
        {% for img in active_images %}
            <a href="{{ img.image.url }}" target="_blank">
                <img 
                    src="{{ img.image.url }}" 
                    alt="Portada del post {{ img.id }}" 
                    class="w-[400px] object-cover aspect-[16/9]">
            </a>
        {% endfor %}
    </div>
{% endif %}

<h3 class="text-2xl uppercase font-bold">{{ post.title }}</h3>

<p>{{ post.content }}</p>
<p>Publicado por: <strong class="font-bold">{{ post.author.username }}</strong></p>
<p>Fecha de publicación: {{ post.creation_date }}</p>
<p>Comentarios permitidos: {{ post.allow_comments|yesno:"Si,No" }}</p>

<div class="flex mt-8 gap-4">
    <a 
        class="bg-blue-500 text-white p-2 rounded-lg"
        href="{% url 'post:post_update' slug=post.slug %}">
        Editar post
    </a>
    <a
        class="bg-red-500 text-white p-2 rounded-lg"
        href="{% url 'post:post_delete' slug=post.slug %}">
        Eliminar post
    </a>
</div>

<!-- Listado de comentarios -->
<h4 class="mt-8 mb-4">Comentarios</h4>
{% if post.comments.count > 0 %}
    <ul>
        {% for comment in post.comments.all %}
        <li class="mb-8">
            {% if comment.id == editing_comment_id %}
                <!-- Formulario de actualización -->
                <form method="post" action="{% url 'post:comment_update' comment.id %}">
                    {% csrf_token %}
                    <p class="flex flex-col">{{ edit_comment_form.content.label_tag }} {{ edit_comment_form.content }}</p>
                    <button type="submit" class="text-blue-500">Actualizar</button>
                    <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
                </form>
            {% elif comment.id == deleting_comment_id %}
                <!-- Formulario de confirmación de eliminación -->
                <form method="post" action="{% url 'post:comment_delete' comment.id %}">
                    {% csrf_token %}
                    <p>¿Estás seguro de que deseas eliminar este comentario?</p>
                    <button type="submit" class="text-blue-500">Confirmar</button>
                    <a href="{% url 'post:post_detail' post.slug %}" class="text-red-500">Cancelar</a>
                </form>
            {% else %}
                <!-- Comentario -->
                <p>{{ comment.content }}</p>
                <small>Escrito por <strong>{{ comment.author.username }}</strong> el 
                    <p>{{comment.creation_date}}</p>
                </small>
                {% if comment.author == user %}
                    <a href="?edit_comment={{ comment.id }}" class="text-blue-500">Editar</a>
                    <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
                {% endif %}
                {% if user.is_collaborator and post.author == user and not comment.author.is_admin and not comment.author.is_superuser or user.is_superuser or user.is_admin %}
                    <a href="?delete_comment={{ comment.id }}" class="text-red-500">Eliminar</a>
                {% endif %}
            {% endif %}
        </li>
        <hr>
        {% endfor %}
    </ul>
{% else %}
    <p>No hay comentarios aún.</p>
{% endif %}

{% if user.is_authenticated %}
    <h4>Agregar un comentario</h4>
    <form method="post" action="{% url 'post:comment_create' post.slug %}">
        {% csrf_token %}
        <p class="flex flex-col mt-4 mb-8">{{ add_comment_form.content.label_tag }}</p>
        <p>{{ add_comment_form.content }}</p>
        <button type="submit" class="bg-blue-500 text-white p-2 rounded-lg">Agregar comentario</button>
    </form>
{% else %}
    <p>
        <a href="{% url 'user:auth_login' %}?next={{ request.path }}" class="hover:text-blue-500">
            Iniciar sesión
        </a> para agregar un comentario.
    </p>
{% endif %}

{% endblock content %}

blog/templates/post/post_list.html
{% extends 'layouts/post_layout.html' %}

{% block title %}Post | BLOG TEJER{% endblock title %}

{% block content %}
<form method="get" class="flex flex-wrap sm:flex-nowrap gap-4 mb-6">
    <div class="w-full">
        {{ filter_form.search_query }}
    </div>
<div class="w-full sm:w-[380px]">
    <select name="category" class="w-full p-2 rounded-lg">
        <option value="">Todas las categorías</option>
        {% for category in categories %}
        <option value="{{ category.id }}">{{ category.title }}</option>
        {% endfor %}
    </select>
</div>
<button type="submit" class="w-full sm:w-[280px] bg-blue-500 text-white p-2
rounded-lg">Buscar</button>
</form>

<div class="grid grid-cols-1 gap-6">
    {% for post in posts %}
        <div class="bg-gray-800 text-white rounded-2xl p-6">
            <h3 class="text-2xl uppercase font-bold">{{post.title}}</h3>
            {% if post.images.exists %}
                <img width="100px" src="{{ post.images.first.image.url }}" alt="Imagen del post">
            {% endif %}
            <p>{{ post.content }}</p>
            <p>Publicado por: <strong class="font-bold">{{ post.author.username}}
            </strong></p>
            <p>Fecha de publicacion: {{ post.creation_date }}</p>
            <p>Comentarios permitidos:  {{ post.allow_comments|yesno:"Si,No" }} </p>
            <p>categorias: {{post.category}}</p>
            <div class="flex gap-2 mt-8">
                <a 
                class="bg-red-500 text-white p-2 rounded-lg"
                href="{% url 'post:post_detail' slug=post.slug %}"
                >Ver post</a>
                <a 
                class="bg-red-500 text-white p-2 rounded-lg"
                href="{% url 'post:post_delete' slug=post.slug %}"
                >Eliminar post</a>
            </div>
        </div>
        {% endfor %}
    </div>
<!-- Controles de paginación -->
<div class="mt-4">
    {% if is_paginated %}
    <div class="flex justify-center items-center gap-2">
        {% if pagination.previous_page %}
        <a href="{{ pagination.previous_page }}" class="w-16 text-xs text-center
bg-blue-500 text-white p-1 rounded-md">Anterior</a>
        {% else %}
        <span class="w-16 text-xs text-center bg-gray-500 text-white p-1
rounded-md">Anterior</span>
        {% endif %}

        <span class="w-10 text-center text-lg font-semibold">{{ page_obj.number }}
</span>
        {% if pagination.next_page %}
        <a href="{{ pagination.next_page }}" class="w-16 text-xs text-center bg
blue-500 text-white p-1 rounded-md">Siguiente</a>
        {% else %}
        <span class="w-16 text-xs text-center bg-gray-500 text-white p-1
rounded-md">Siguiente</span>
        {% endif %}
        </div>
    {% endif %}
</div>

{% endblock content %}

blog/templates/post/post_update.html
{% extends 'layouts/post_layout.html' %}
{% block title %}ACTUALIZAR Post | BLOG IA{% endblock title %}
{% block content %}
<h2>Actualizar: {{ form.instance.title }}</h2>
<form
 method="post"
 enctype="multipart/form-data"
 class="flex flex-col justify-center items-start w-[400px] gap-4"
>
 {% csrf_token %}
 <div class="flex flex-col">{{ form.title.label_tag }} {{ form.title }}</div>
 <div class="flex flex-col">
 {{ form.content.label_tag }} {{ form.content }}
 </div>
 <div class="flex gap-4">
 {{ form.allow_comments.label_tag }} {{ form.allow_comments }}
 </div>
 <h3>Imágenes cargadas</h3>
 <div class="flex flex-col gap-4">
 {% for active_img in form.active_images %} 
 {% comment %} <p>{{ active_img.id }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.post }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.post.author }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.image }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.image.url }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.active }}</p> {% endcomment %} 
 {% comment %} <p>{{ active_img.creation_date }}</p> {% endcomment %}
 <p>
 <a href="{{ active_img.image.url }}" target="_blank">
 <img
 class="inline-flex w-[200px] aspect-[16/9] object-cover"
 src="{{ active_img.image.url }}"
 alt="Portada {{ active_img.id }} del post"
 />
 </a>
 <input
 type="checkbox"
 name="keep_image_{{ active_img.id }}"
 id="keep_image_{{ active_img.id }}"
 checked
 />
 <label for="keep_image_{{ active_img.id }}">Activa</label>
 </p>
 {% endfor %}
 </div>
 <h3>Cargar nuevas imágenes</h3>
 <input type="file" name="images" multiple />
 <div class="flex gap-2">
 <a href="{% url 'post:post_detail' slug=form.instance.slug %}"
 class="bg-red-500 text-white p-2 rounded-md">Cancelar</a>
 <button type="submit" class="bg-blue-500 text-white p-2 rounded-md">
 Guardar cambios
 </button>
 </div>
</form>
{% comment %} <a href="javascript:history.back()">Cancelar</a> {% endcomment %}
{% endblock content %}